site_name: Global AI Community | Docs

nav:
  - Getting started : index.md
  - Chapter Management:
    - Introduction: chapters/intro.md
    - Onboarding: chapters/01-Onboarding.md
    - Managing Events: chapters/events.md
    - Global AI Bootcamp 2025: chapters/03-bootcamp.md


plugins:
  - glightbox
  - mkdocs-video
  
theme:
  name: material
  logo: media/icon.png
  favicon: media/icon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 0
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg



extra_css:
  - css/custom.css